FONT_NAME="ocodo-mono-dotzero"
FONT_PACKAGE="@ocodo/ocodo-mono-dotzero"
FONT_FILE="fonts/OcodoMonoDotZero-Light.ttf"
FONT_TTF="fonts/OcodoMonoDotZero-Light.ttf"
OUT_DIR="dist"
LIB_VERSION="0.1.0"
HEIGHTS="16 24 32 48 64 96"
